# Copyright 2010 Fumitoshi Ukai
# Use of this source code is governed by a BSD-style

# goinstall godentaku.googlecode.com/hg/godentaku でパッケージのインストール
# gomake でビルド
# ./godentaku で実行

include $(GOROOT)/src/Make.inc

# TARGに実行ファイル名を設定します。
TARG=godentaku
# GOFILESにソースファイル一式を設定します。
GOFILES=\
	main.go

# コマンドの場合 Make.cmdをincludeします。
include $(GOROOT)/src/Make.cmd
